In [ ]:
import numpy as np
import pandas as pd

data = {
    'Emplotee id': [45, 78 ,56 ,12, 7, 68, 23, 45, 89, 75, 47 ,62],
    'Gender': ['Male', 'Female', 'Female', 'Male', 'Female', 'Female', 'Male', 'Female', 'Male', 'Female', 'Female', 'Male'],
    'Remarks' : ['Nice', 'Good', 'Great', 'Great', 'Nice', 'Great', 'Good', 'Nice', 'Great', 'Nice', 'Good', 'Nice']
}
data2 = pd.DataFrame(data)
data2.head()

   Emplotee id  Gender Remarks
0           45    Male    Nice
1           78  Female    Good
2           56  Female   Great
3           12    Male   Great
4            7  Female    Nice

In [ ]:
print(data2['Gender'].unique())
print(data2['Remarks'].unique())

['Male' 'Female']
['Nice' 'Good' 'Great']

In [ ]:
#Count of Elements in the Column

print(data2['Gender'].value_counts())
print(data2['Remarks'].value_counts())

Gender
Female    7
Male      5
Name: count, dtype: int64
Remarks
Nice     5
Great    4
Good     3
Name: count, dtype: int64

In [ ]:
one_hot_encoded_data = pd.get_dummies(data2, columns=['Remarks', 'Gender'])
print(one_hot_encoded_data)

    Emplotee id  Remarks_Good  Remarks_Great  Remarks_Nice  Gender_Female  \
0            45         False          False          True          False
1            78          True          False         False           True
2            56         False           True         False           True
3            12         False           True         False          False
4             7         False          False          True           True
5            68         False           True         False           True
6            23          True          False         False          False
7            45         False          False          True           True
8            89         False           True         False          False
9            75         False          False          True           True
10           47          True          False         False           True
11           62         False          False          True          False

    Gender_Male
0          True
1         False
2         False
3          True
4         False
5         False
6          True
7         False
8          True
9         False
10        False
11         True

In [ ]:
one_hot_encoded_data

,Emplotee id,Remarks_Good,Remarks_Great,Remarks_Nice,Gender_Female,Gender_Male
0,45,False,False,True,False,True
1,78,True,False,False,True,False
2,56,False,True,False,True,False
3,12,False,True,False,False,True
4,7,False,False,True,True,False
5,68,False,True,False,True,False
6,23,True,False,False,False,True
7,45,False,False,True,True,False
8,89,False,True,False,False,True
9,75,False,False,True,True,False
10,47,True,False,False,True,False
11,62,False,False,True,False,True

In [ ]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

#Building a dummy employee dataset for example
data = {'Employee id': [10, 20, 15, 25, 30],
        'Gender': ['M', 'F', 'F', 'M', 'F'],
        'Remarks': ['Good', 'Nice', 'Good', 'Great', 'Nice'],
        }
df = pd.DataFrame(data)
#Print the dataframe:
print(f"Employee data : \n{df}")

categorical_columns = df.select_dtypes(include=['object']).columns.tolist()
encoder = OneHotEncoder(sparse_output=False)

one_hot_encoded = encoder.fit_transform(df[categorical_columns])
one_hot_df = pd.DataFrame(one_hot_encoded, columns=encoder.get_feature_names_out(categorical_columns))

df_endcoded = pd.concat([df, one_hot_df], axis=1)

#Drop the original categorical columns
df_endcoded = df_endcoded.drop(categorical_columns, axis=1)

Employee data :
   Employee id Gender Remarks
0           10      M    Good
1           20      F    Nice
2           15      F    Good
3           25      M   Great
4           30      F    Nice